const shoppingListService = require('../src/shopping-list-service');
const knex = require('knex');

// id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
// name TEXT NOT NULL,
// price DECIMAL(19, 2) NOT NULL,
// date_added TIMESTAMP DEFAULT now() NOT NULL,
// checked BOOLEAN DEFAULT false NOT NULL,
// category grocery NOT NULL


describe('Shopping List service object', () => {
  let db;
  let testLists = [
    {
      id: 1,
      name: 'test 1',
      price: 20.20,
      date_added: new Date(),
      checked: false,
      category: 'snack'
    },
    {
      id: 2,
      name: 'test 2',
      price: 20.30,
      date_added: new Date(),
      checked: false,
      category: 'snack'
    },
    {
      id: 3,
      name: 'test 3',
      price: 20.44,
      date_added: new Date(),
      checked: false,
      category: 'snack'
    }
  ];
  // ? before testing set db to be our knex config
  before(() => {
    db = knex({
      client: 'pg',
      connection: process.env.DB_URL
    });
  });


});