insert into blogful_articles (title, date_published, content) values ('Sandgrouse, yellow-throated', '12/20/2019', 'Pterocles gutturalis');
insert into blogful_articles (title, date_published, content) values ('Southern sea lion', '4/14/2020', 'Otaria flavescens');
insert into blogful_articles (title, date_published, content) values ('Dolphin, striped', '11/1/2019', 'Stenella coeruleoalba');
insert into blogful_articles (title, date_published, content) values ('Weaver, red-billed buffalo', '7/24/2020', 'Bubalornis niger');
insert into blogful_articles (title, date_published, content) values ('Possum, common brushtail', '11/11/2019', 'Trichosurus vulpecula');
insert into blogful_articles (title, date_published, content) values ('Puffin, horned', '6/8/2020', 'Fratercula corniculata');
insert into blogful_articles (title, date_published, content) values ('Stilt, black-winged', '12/18/2019', 'Himantopus himantopus');
insert into blogful_articles (title, date_published, content) values ('Fox, crab-eating', '6/12/2020', 'Dusicyon thous');
insert into blogful_articles (title, date_published, content) values ('Brown antechinus', '6/10/2020', 'Antechinus flavipes');
insert into blogful_articles (title, date_published, content) values ('Ovenbird', '4/18/2020', 'Seiurus aurocapillus');
insert into blogful_articles (title, date_published, content) values ('Grenadier, purple', '3/15/2020', 'Uraeginthus granatina');
insert into blogful_articles (title, date_published, content) values ('Mouflon', '8/10/2020', 'Ovis musimon');
insert into blogful_articles (title, date_published, content) values ('Little grebe', '5/29/2020', 'Tachybaptus ruficollis');
insert into blogful_articles (title, date_published, content) values ('Sambar', '1/24/2020', 'Cervus unicolor');
insert into blogful_articles (title, date_published, content) values ('Cobra, cape', '3/2/2020', 'Naja nivea');
insert into blogful_articles (title, date_published, content) values ('Common raccoon', '2/10/2020', 'Procyon lotor');
insert into blogful_articles (title, date_published, content) values ('Loris, slender', '7/16/2020', 'Loris tardigratus');
insert into blogful_articles (title, date_published, content) values ('Sally lightfoot crab', '6/23/2020', 'Graspus graspus');
insert into blogful_articles (title, date_published, content) values ('Savannah deer (unidentified)', '6/26/2020', 'unavailable');
insert into blogful_articles (title, date_published, content) values ('Raccoon dog', '7/25/2020', 'Nyctereutes procyonoides');
